
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost"
              - "http://localhost:80"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: book-service-route
          uri: lb://book-service
          predicates:
            - Path=/v1/books/**
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/v1/users/**
        - id: borrow-service-route
          uri: lb://borrow-service
          predicates:
            - Path=/v1/services/**
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
